// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions are not supported for this platform.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        //TODO: IOS
        // return ios;
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwF4n4Whs0FPvKFH1FSiyk9G9mlMnIx6w',
    appId: '1:434722891078:android:24d563f8f09c1ef3743147',
    messagingSenderId: '434722891078',
    projectId: 'mapify-a24be',
    storageBucket: 'mapify-a24be.appspot.com',
  );

//TODO: IOS
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: "AIzaSyDac1glenU9_42fgUptJb5yeu7pgE3pxPU",
  //   appId: "1:963667818091:ios:ce04e15417ed2f39f2232e",
  //   messagingSenderId: "963667818091",
  //   projectId: "wasel-app-add9d",
  // );
}
